/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import conexion.Conexion;
import controlador.ReportesController;
import javax.swing.JOptionPane;
import controlador.VehiculoController;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import modelo.Vehiculo;
import java.sql.*;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ortiz
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    private int idVehiculo = 0;
    private double valorAPagar = 0;
    
    public FormMenu() {
        initComponents();
        this.setSize(900, 550);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Sistema de Parqueadero");
        
        jLabel_info.setVisible(false);

        //Cargar tabla de vehiculos
        this.CargarTablaVehiculos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_logo = new javax.swing.JLabel();
        jButton_cerrar_sesion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_footer = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_registrar_vehiculo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_propietario = new javax.swing.JTextField();
        jTextField_placa = new javax.swing.JTextField();
        jComboBox_tipo_vehiculo = new javax.swing.JComboBox<>();
        jButton_registrar = new javax.swing.JButton();
        jPanel_retirar_vehiculo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_info = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_placa_retiro = new javax.swing.JTextField();
        jButton_buscar_placa = new javax.swing.JButton();
        jButton_retirar = new javax.swing.JButton();
        jLabel_propietario = new javax.swing.JLabel();
        jLabel_hora_entrada = new javax.swing.JLabel();
        jLabel_hora_salida = new javax.swing.JLabel();
        jLabel_valor_pagar = new javax.swing.JLabel();
        jPanel_administrar_vehiculo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_busqueda_criterio = new javax.swing.JTextField();
        jDateChooser_fecha_busqueda = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_vehiculos = new javax.swing.JTable();
        jButton_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(18, 61, 104));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PARQUEADERO VON HUMBOLDT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 70));

        jLabel_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jLabel_logo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 190, 160));

        jButton_cerrar_sesion.setBackground(new java.awt.Color(189, 24, 34));
        jButton_cerrar_sesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_cerrar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        jButton_cerrar_sesion.setText("CERRAR SESIÓN");
        jButton_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrar_sesionActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_cerrar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 210, 30));

        jButton1.setBackground(new java.awt.Color(18, 61, 104));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("MAS INFORMACIÓN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("¡BIENVENIDO!");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 550));

        jPanel2.setBackground(new java.awt.Color(18, 61, 104));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_footer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_footer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_footer.setText("© 2024 Corporación Universitaria Empresarial Alexander Von Humboldt");
        jPanel2.add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 400, 30));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(18, 61, 104));

        jPanel_registrar_vehiculo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_registrar_vehiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(18, 61, 104));
        jLabel2.setText("Registro de ingreso de vehiculos al parqueadero");
        jPanel_registrar_vehiculo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(18, 61, 104));
        jLabel3.setText("Propietario:");
        jPanel_registrar_vehiculo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(18, 61, 104));
        jLabel4.setText("Tipo de vehiculo: ");
        jPanel_registrar_vehiculo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(18, 61, 104));
        jLabel5.setText("Placa: ");
        jPanel_registrar_vehiculo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 30));

        jTextField_propietario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField_propietario.setForeground(new java.awt.Color(18, 61, 104));
        jPanel_registrar_vehiculo.add(jTextField_propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 230, 30));

        jTextField_placa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField_placa.setForeground(new java.awt.Color(18, 61, 104));
        jTextField_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_placaKeyPressed(evt);
            }
        });
        jPanel_registrar_vehiculo.add(jTextField_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 230, 30));

        jComboBox_tipo_vehiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_tipo_vehiculo.setForeground(new java.awt.Color(18, 61, 104));
        jComboBox_tipo_vehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Automovil", "Motocicleta" }));
        jPanel_registrar_vehiculo.add(jComboBox_tipo_vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 230, 30));

        jButton_registrar.setBackground(new java.awt.Color(18, 61, 104));
        jButton_registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_registrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coche-revisado.png"))); // NOI18N
        jButton_registrar.setText("REGISTRAR");
        jButton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarActionPerformed(evt);
            }
        });
        jPanel_registrar_vehiculo.add(jButton_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 230, 30));

        jTabbedPane1.addTab("Registrar Vehiculo", jPanel_registrar_vehiculo);

        jPanel_retirar_vehiculo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_retirar_vehiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(18, 61, 104));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Retiro de Vehiculo del Parqueadero");
        jPanel_retirar_vehiculo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 250, 30));

        jLabel_info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_info.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_info.setText("Vehiculo Retirado");
        jPanel_retirar_vehiculo.add(jLabel_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 250, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(18, 61, 104));
        jLabel10.setText("Placa:");
        jPanel_retirar_vehiculo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 100, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(18, 61, 104));
        jLabel11.setText("Propietario:");
        jPanel_retirar_vehiculo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 100, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(18, 61, 104));
        jLabel12.setText("Hora Entrada:");
        jPanel_retirar_vehiculo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 100, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(18, 61, 104));
        jLabel13.setText("Hora Salida:");
        jPanel_retirar_vehiculo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 100, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(18, 61, 104));
        jLabel14.setText("Valor a Pagar:");
        jPanel_retirar_vehiculo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 100, 30));

        jTextField_placa_retiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField_placa_retiro.setForeground(new java.awt.Color(204, 0, 0));
        jPanel_retirar_vehiculo.add(jTextField_placa_retiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 125, 30));

        jButton_buscar_placa.setBackground(new java.awt.Color(18, 61, 104));
        jButton_buscar_placa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_buscar_placa.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscar_placa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        jButton_buscar_placa.setText("BUSCAR");
        jButton_buscar_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscar_placaActionPerformed(evt);
            }
        });
        jPanel_retirar_vehiculo.add(jButton_buscar_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 125, 30));

        jButton_retirar.setBackground(new java.awt.Color(189, 24, 34));
        jButton_retirar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_retirar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_retirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coche.png"))); // NOI18N
        jButton_retirar.setText("RETIRAR");
        jButton_retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_retirarActionPerformed(evt);
            }
        });
        jPanel_retirar_vehiculo.add(jButton_retirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 250, 30));

        jLabel_propietario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel_propietario.setForeground(new java.awt.Color(18, 61, 104));
        jLabel_propietario.setText("ALGUIEN");
        jPanel_retirar_vehiculo.add(jLabel_propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 200, 30));

        jLabel_hora_entrada.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel_hora_entrada.setForeground(new java.awt.Color(18, 61, 104));
        jLabel_hora_entrada.setText("00:00:00");
        jPanel_retirar_vehiculo.add(jLabel_hora_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 200, 30));

        jLabel_hora_salida.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel_hora_salida.setForeground(new java.awt.Color(18, 61, 104));
        jLabel_hora_salida.setText("00:00:00");
        jPanel_retirar_vehiculo.add(jLabel_hora_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 200, 30));

        jLabel_valor_pagar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel_valor_pagar.setForeground(new java.awt.Color(18, 61, 104));
        jLabel_valor_pagar.setText("$ 0.00");
        jPanel_retirar_vehiculo.add(jLabel_valor_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 200, 30));

        jTabbedPane1.addTab("Retirar Vehiculo", jPanel_retirar_vehiculo);

        jPanel_administrar_vehiculo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_administrar_vehiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(18, 61, 104));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Administracion de Vehiculos del Parqueadero");
        jPanel_administrar_vehiculo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(18, 61, 104));
        jLabel7.setText("Fecha");
        jPanel_administrar_vehiculo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(18, 61, 104));
        jLabel8.setText("Placa/Propietario:");
        jPanel_administrar_vehiculo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        jTextField_busqueda_criterio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_busqueda_criterio.setForeground(new java.awt.Color(18, 61, 104));
        jPanel_administrar_vehiculo.add(jTextField_busqueda_criterio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 200, 30));

        jDateChooser_fecha_busqueda.setForeground(new java.awt.Color(18, 61, 104));
        jDateChooser_fecha_busqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel_administrar_vehiculo.add(jDateChooser_fecha_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 140, 30));

        jTable_vehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_vehiculos);

        jPanel_administrar_vehiculo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 570, 230));

        jButton_buscar.setBackground(new java.awt.Color(18, 61, 104));
        jButton_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        jButton_buscar.setText("BUSCAR");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });
        jPanel_administrar_vehiculo.add(jButton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 130, 30));

        jTabbedPane1.addTab("Administrar Vehiculos", jPanel_administrar_vehiculo);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 590, 400));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 630, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrar_sesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_cerrar_sesionActionPerformed

    private void jButton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarActionPerformed
        
        String placa = jTextField_placa.getText().trim();
        String propietario = jTextField_propietario.getText().trim();
        
        if (placa.isEmpty() || propietario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese Datos");
        } else {

            //Validar seleccion del tipo de vehiculo
            String tipo_vehiculo = jComboBox_tipo_vehiculo.getSelectedItem().toString().trim();
            if (tipo_vehiculo.equalsIgnoreCase("Seleccione:")) {
                JOptionPane.showMessageDialog(null, "Seleccione el tipo de vehiculo");
            } else {
                
                VehiculoController controlVehiculo = new VehiculoController();
                Vehiculo vehiculo = new Vehiculo();
                
                vehiculo.setPlaca(placa);
                vehiculo.setPropietario(propietario);
                vehiculo.setTipoVehiculo(tipo_vehiculo);

                //fecha y hora de entrada
                DateFormat dateFormatFecha = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                Calendar calendar = Calendar.getInstance();
                Date date = calendar.getTime();
                String fecha = dateFormatFecha.format(date);
                
                vehiculo.setHoraEntrada(fecha);
                vehiculo.setHoraSalida(null);
                vehiculo.setEstado("INGRESADO");
                
                if (controlVehiculo.guardar(vehiculo)) {
                    JOptionPane.showMessageDialog(null, "*** Ingreso de Vehiculo Registrado ***");
                    //cargar la tabla de vehiculos 
                    this.CargarTablaVehiculos();

                    //Limpiar campos
                    jTextField_placa.setText("");
                    jTextField_propietario.setText("");
                    jComboBox_tipo_vehiculo.setSelectedItem("Seleccione:");
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Registrar Ingreso de Vehiculo");
                }
                
            }
            
        }
        

    }//GEN-LAST:event_jButton_registrarActionPerformed

    private void jTextField_placaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_placaKeyPressed
        
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextField_propietario.requestFocus();
        }

    }//GEN-LAST:event_jTextField_placaKeyPressed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        
        String PlacaPropietarioBusqueda = jTextField_busqueda_criterio.getText().trim();
        Date fechaBusqueda = jDateChooser_fecha_busqueda.getDate();
        String fechaComoCadena = "";
        
        if (fechaBusqueda != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            fechaComoCadena = sdf.format(fechaBusqueda);
        }
        
        if (PlacaPropietarioBusqueda.isEmpty() && fechaComoCadena.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese Placa o Propietario para busqueda");
            this.CargarTablaVehiculos();
            
        } else {
            
            VehiculoController vehiculoController = new VehiculoController();
            
            vehiculoController.buscarVehiculosPlacaFecha(PlacaPropietarioBusqueda, fechaComoCadena);
            ArrayList<Vehiculo> listaVehiculo = vehiculoController.listaVehiculo;
            
            DefaultTableModel model = new DefaultTableModel();
            
            this.jTable_vehiculos = new JTable(model);
            this.jScrollPane1.setViewportView(this.jTable_vehiculos);
            model.addColumn("N°");
            model.addColumn("Placa");
            model.addColumn("Propietario");
            model.addColumn("Tipo de Vehiculo");
            model.addColumn("Valor Pagado");
            model.addColumn("Estado");
            
            Object fila[] = new Object[6];
            for (Vehiculo vehiculo : listaVehiculo) {
                fila[0] = vehiculo.getIdVehiculo();
                fila[1] = vehiculo.getPlaca();
                fila[2] = vehiculo.getPropietario();
                fila[3] = vehiculo.getTipoVehiculo();
                fila[4] = vehiculo.getValorPagado();
                fila[5] = vehiculo.getEstado();
                model.addRow(fila);
                
            }

            //evento
            jTable_vehiculos.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    int fila_point = jTable_vehiculos.rowAtPoint(e.getPoint());
                    int columna_point = 0;
                    
                    if (fila_point > -1) {
                        idVehiculo = (int) model.getValueAt(fila_point, columna_point);
                        EnviarDatosVehiculoSeleccionado(idVehiculo);//metodo
                    }
                    
                }
                
            });
            
        }
        //Limpiar campo
        jTextField_busqueda_criterio.setText("");
        

    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jButton_buscar_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscar_placaActionPerformed
        
        String placaBuscar = jTextField_placa_retiro.getText().trim();
        String estado = "", salida = "";
        double valor = 0.00;
        
        if (placaBuscar.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Placa");
            
        } else {
            Connection cn = Conexion.conectar();
            String sql = "select * from tb_vehiculo where placa = '" + placaBuscar + "'";
            Statement st;
            
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Calendar calendar = Calendar.getInstance();
            Date date = calendar.getTime();
            
            try {
                st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                
                if (rs.next()) {
                    idVehiculo = rs.getInt("id_vehiculo");
                    jLabel_propietario.setText(rs.getString("propietario"));
                    jLabel_hora_entrada.setText(rs.getString("hora_entrada"));
                    salida = rs.getString("hora_salida");
                    valor = rs.getDouble("valor_pagado");
                    estado = rs.getString("estado");

                    //fecha y hora de entrada
                    String tiempoIngresado = rs.getString("hora_entrada");
                    Date tiempo = dateFormat.parse(tiempoIngresado);
                    int minutosACobrar = (int) (date.getTime() - tiempo.getTime()) / 60000;
                    
                    if (rs.getString("tipo_vehiculo").equals("Automovil")) {
                        if (minutosACobrar < 60) {
                            valorAPagar = 100; //valor en pesos
                            //si el vehiculo tiene menos de una hora, el valor será de 100 pesos.
                            //de ahi en adelante, el valor será 100 pesos por minuto 6000 pesos por hora

                        } else {
                            valorAPagar = ((minutosACobrar - 60) * 100) + 100;
                            
                        }
                    } else if (rs.getString("tipo_vehiculo").equals("Motocicleta")) {
                        if (minutosACobrar < 60) {
                            valorAPagar = 50; //valor en pesos
                            //si el vehiculo tiene menos de una hora, el valor será de 50 pesos.
                            //de ahi en adelante, el valor será 50 pesos por minuto 3000 pesos por hora

                        } else {
                            valorAPagar = ((minutosACobrar - 60) * 50) + 50;
                            
                        }
                        
                    }

                    //FECHA Y HORA ACTUAL
                    String fecha = dateFormat.format(date);
                    jLabel_hora_salida.setText(fecha);
                    jLabel_valor_pagar.setText("$ " + valorAPagar);
                    if (estado.equalsIgnoreCase("EGRESADO")) {
                        jButton_retirar.setEnabled(false);
                        jLabel_info.setVisible(true);
                        jLabel_hora_salida.setText(salida);
                        jLabel_valor_pagar.setText(String.valueOf(valor));
                        
                    } else {
                        jButton_retirar.setEnabled(true);
                        jLabel_info.setVisible(false);
                        
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Placa no registrada");
                    jLabel_propietario.setText("ALGUIEN");
                    jLabel_hora_entrada.setText("00:00:00");
                    jLabel_hora_salida.setText("00:00:00");
                    jLabel_valor_pagar.setText("$ 0.00");
                }
                
            } catch (SQLException e) {
                System.out.println("Error al buscar datos del vehiculo ingresado: " + e);
            } catch (ParseException ex) {
                Logger.getLogger(FormMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        

    }//GEN-LAST:event_jButton_buscar_placaActionPerformed

    private void jButton_retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_retirarActionPerformed
        
        if (jLabel_propietario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Busque un vehiculo para retirar");
            
        } else {
            
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Calendar calendar = Calendar.getInstance();
            Date date = calendar.getTime();
            String fecha = dateFormat.format(date);
            //Actualizamos los datos del vehiculo
            Vehiculo vehiculo = new Vehiculo();
            VehiculoController vehiculoController = new VehiculoController();
            
            vehiculo.setHoraSalida(fecha);//hora de salida
            vehiculo.setValorPagado(valorAPagar);
            vehiculo.setEstado("EGRESADO");
            
            if (vehiculoController.actualizar(vehiculo, idVehiculo)) {
                JOptionPane.showMessageDialog(null, "Vehiculo Retirado con Exito");
                this.CargarTablaVehiculos();
                
                jTextField_placa_retiro.setText("");
                jLabel_propietario.setText("");
                jLabel_hora_entrada.setText("00:00:00");
                jLabel_hora_salida.setText("00:00:00");
                jLabel_valor_pagar.setText("$ 0.00");

                //metodo para crear el ticket en pdf
                ReportesController ticket = new ReportesController();
                ticket.TicketRetiro(idVehiculo);
                
            } else {
                System.out.println("Error al actualizar datos del vehiculo");
                
            }
            
        }
        

    }//GEN-LAST:event_jButton_retirarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Desktop.getDesktop().browse(new URL ("https://parqueaderoavh.neocities.org/ParqueaderoVonHumboldt/parqueaderohumboldt/").toURI());
        }catch(Exception e)
        {}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_buscar_placa;
    private javax.swing.JButton jButton_cerrar_sesion;
    private javax.swing.JButton jButton_registrar;
    private javax.swing.JButton jButton_retirar;
    private javax.swing.JComboBox<String> jComboBox_tipo_vehiculo;
    private com.toedter.calendar.JDateChooser jDateChooser_fecha_busqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JLabel jLabel_hora_entrada;
    private javax.swing.JLabel jLabel_hora_salida;
    private javax.swing.JLabel jLabel_info;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_propietario;
    private javax.swing.JLabel jLabel_valor_pagar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_administrar_vehiculo;
    private javax.swing.JPanel jPanel_registrar_vehiculo;
    private javax.swing.JPanel jPanel_retirar_vehiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_vehiculos;
    private javax.swing.JTextField jTextField_busqueda_criterio;
    private javax.swing.JTextField jTextField_placa;
    private javax.swing.JTextField jTextField_placa_retiro;
    private javax.swing.JTextField jTextField_propietario;
    // End of variables declaration//GEN-END:variables

    //metodo para mostrar todos los vehiculos registrados
    private void CargarTablaVehiculos() {
        Connection cn = Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select id_vehiculo, placa, propietario, tipo_vehiculo, valor_pagado, estado from tb_vehiculo";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            this.jTable_vehiculos = new JTable(model);
            this.jScrollPane1.setViewportView(this.jTable_vehiculos);
            
            model.addColumn("N°");//ID
            model.addColumn("Placa");
            model.addColumn("Propietario");
            model.addColumn("Tipo de Vehiculo");
            model.addColumn("Valor Pagado");
            model.addColumn("Estado");
            
            while (rs.next()) {
                Object fila[] = new Object[6];
                for (int i = 0; i < 6; i++) {
                    fila[i] = rs.getObject(i + 1);
                    
                }
                model.addRow(fila);
                
            }
            
        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla de vehiculos: " + e);
        }

        //evento
        jTable_vehiculos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_vehiculos.rowAtPoint(e.getPoint());
                int columna_point = 0;
                
                if (fila_point > -1) {
                    idVehiculo = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosVehiculoSeleccionado(idVehiculo);//metodo
                }
                
            }
            
        });
        
    }

    //metodo que envia datos seleccionados
    private void EnviarDatosVehiculoSeleccionado(int idVehiculo) {
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select * from tb_vehiculo where id_vehiculo = '" + idVehiculo + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                DetalleVehiculo detalle = new DetalleVehiculo();
                detalle.setVisible(true);
                
                DetalleVehiculo.jLabel_placa_detalle.setText(rs.getString("placa"));
                DetalleVehiculo.jLabel_propietario_detalle.setText(rs.getString("propietario"));
                DetalleVehiculo.jLabel_hora_entrada_detalle.setText(rs.getString("hora_entrada"));
                DetalleVehiculo.jLabel_hora_salida_detalle.setText(rs.getString("hora_salida"));
                DetalleVehiculo.jLabel_valor_pagado_detalle.setText(rs.getString("valor_pagado"));
                DetalleVehiculo.jLabel_tipo_vehiculo_detalle.setText(rs.getString("tipo_vehiculo"));
                DetalleVehiculo.jLabel_estado_detalle.setText(rs.getString("estado"));
            }
            
        } catch (SQLException e) {
            System.out.println("Error al seleccionar vehiculo: " + e);
        }
        
    }
    
}
